name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Apifox CLI
      run: npm install -g apifox-cli

    - name: Running Test Scenario
      run: apifox run https://api.apifox.com/api/v1/projects/2581514/api-test/ci-config/458296/detail?token=xVuaJHoyzcGZu39jZ4d2UK -r html,cli
